-- SELECT * FROM users WHERE email = '';
-- SELECT count(*) FROM users WHERE address = 'Chui' AND email = '';
-- SELECT login, phone_number FROM users WHERE profession = 'Web Developer';
-- UPDATE users
-- SET address = 'user@gmail.com.' WHERE address = 'False';
-- SELECT login, country FROM users WHERE profession = 'Unemployed';
-- UPDATE users
-- SET phone_number = '0707012233' WHERE phone_number = '%000%';
-- DELETE FROM users WHERE password = '12345' OR password = 'user123б' OR password = 'qwerty';
-- SELECT email FROM users WHERE profession = '.NET Developer';